name: Mirror to GitLab

on:
  push:
    branches:
      - main

jobs:
  push_to_gitlab:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push to GitLab
      env:
        GITLAB_SSH_PRIVATE_KEY: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$GITLAB_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
        git remote add gitlab git@gitlab.com:phatmap234/thisistest.git
        git push --mirror gitlab
